name = "SNaQ"
uuid = "c2bf7a07-44d2-4d11-b5e2-76dc5aa199d6"
authors = ["Claudia Solis-Lemus <crsl4@users.noreply.github.com>", "Paul Bastide <pbastide@users.noreply.github.com>", "Cecile Ane <cecileane@users.noreply.github.com>", "and contributors"]
version = "1.2.6"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
BenchmarkTools = "1.6.0"
CSV = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10"
CairoMakie = "0.13.6"
Combinatorics = "1.0.2"
DataFrames = "1.3"
DataStructures = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18"
DelaunayTriangulation = "1.6.4"
Dierckx = "0.5.4"
Distances = "0.10.12"
Distributions = "0.25.115"
GLMakie = "0.11.7"
GeometryBasics = "0.5.9"
GraphMakie = "0.5.14"
GraphPlot = "0.6.1"
GraphRecipes = "0.5.14"
Graphs = "1.12.0"
Interpolations = "0.15.1"
MultivariateStats = "0.10.3"
NLopt = "0.5.1, 0.6, 1"
PhyloNetworks = "1"
StaticArrays = "0.8.3, 0.9, 0.10, 0.11, 0.12, 1.0"
StatsBase = "0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33, 0.34"
julia = "1.5"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
GraphPlot = "a2cc645c-3eea-5389-862e-a155d0052231"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PhyloPlots = "c0d5b6db-e3fc-52bc-a87d-1d050989ed3b"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ScatteredInterpolation = "3f865c0f-6dca-5f4d-999b-29fe1e7e3c92"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
