[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
PhyloNetworks = "33ad39ac-ed31-50eb-9b15-43d0656eaa72"
PhyloPlots = "c0d5b6db-e3fc-52bc-a87d-1d050989ed3b"
PhyloTraits = "bce24f4f-6725-4ba4-a77f-2b043c8e33c5"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
SNaQ = "c2bf7a07-44d2-4d11-b5e2-76dc5aa199d6"

[sources]
PhyloTraits = {url = "https://github.com/JuliaPhylo/PhyloTraits.jl"}
